### ISSUE TITLE
activeDeadlineSeconds Vs. startingDeadlineSeconds 

### ISSUE THREAD

**Issue by vazudew** [dgkanatsios/CKAD-exercises#169]
Issue: [CronJob - Terminate if Job takes more than 17 S](https://github.com/dgkanatsios/CKAD-exercises/blob/master/c.pod_design.md#create-a-cron-job-with-image-busybox-that-runs-every-minute-and-writes-date-echo-hello-from-the-kubernetes-cluster-to-standard-output-the-cron-job-should-be-terminated-if-it-takes-more-than-17-seconds-to-start-execution-after-its-schedule)

For the question on scheduled CronJob which must be terminated within 17 seconds, my opinion is that we must use activeDeadlineSeconds = 17 seconds and not startingDeadlineSeconds =17s.

**activeDeadlineSeconds** 
Source: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#cron-job-limitations
> another way to terminate a Job is by setting an active deadline. Do this by setting the .spec.activeDeadlineSeconds field of the Job to a number of seconds. The activeDeadlineSeconds applies to the duration of the job, no matter how many Pods are created. Once a Job reaches activeDeadlineSeconds, all of its running Pods are terminated and the Job status will become type: Failed with reason: DeadlineExceeded.

**startingDeadlineSeconds,** 
Source: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#cron-job-limitations
> For example, suppose a CronJob is set to schedule a new Job every one minute beginning at 08:30:00, and its startingDeadlineSeconds field is not set. If the CronJob controller happens to be down from 08:29:00 to 10:21:00, the job will not start as the number of missed jobs which missed their schedule is greater than 100.

> To illustrate this concept further, suppose a CronJob is set to schedule a new Job every one minute beginning at 08:30:00, and its startingDeadlineSeconds is set to 200 seconds. If the CronJob controller happens to be down for the same period as the previous example (08:29:00 to 10:21:00,) the Job will still start at 10:22:00. This happens as the controller now checks how many missed schedules happened in the last 200 seconds (ie, 3 missed schedules), rather than from the last scheduled time until now.

**Comment by vazudew** [comment]
created a PR https://github.com/dgkanatsios/CKAD-exercises/pull/170

**Comment by dgkanatsios** [comment]
thanks!

**Comment by maelfosso** [comment]
Hello @dgkanatsios @vazudew 

I think that the first answer was good

1. @vazudew Please, what you set up there as blockquote is not for **activeDeadlineSeconds** (it's come from _CronJob_ documentation)
2. **startingDeadlineSeconds** was the right answer only because it allows you to stop the CronJob if the after being scheduling it has not yet started after the number of seconds indicated (in our situation **17s**). **activeDeadlineSeconds** is whatever is the situation running or not, the Job will die. And please @vazudew if we take closely the question, we will notice that it's about **after being scheduling** (CronJob property) not after being started (Job property)
3. I suggest you read this article https://medium.com/@hengfeng/what-does-kubernetes-cronjobs-startingdeadlineseconds-exactly-mean-cc2117f9795f which explains with some example how **startingDeadlineSeconds** will stop the CronJob if it has not started after **a number of seconds from its scheduling**

Please, kindly **fix that**, **the first one was the right answer**.I think.
